Repository openshift-assisted/assisted-events-stream, pull requests merged in 2023-10, with the labels that each got.

#48 handle assisted versions
  internal/onprem/event_extractor.go
  internal/onprem/event_extractor_test.go
  internal/onprem/testdata/84364d0aade5461ca41b69f29e7b9181.gz
Labels: approved, lgtm, size/L

#49 MGMT-15798: Upgrade to ubi9 base image in order to have patched glibc package
  Dockerfile
Labels: approved, lgtm, size/XS, jira/valid-reference

#50 ack discarded messages
  internal/onprem/hydrate.go
Labels: approved, lgtm, size/M

#51 add versions only to event notification
  internal/onprem/event_extractor.go
  internal/onprem/event_extractor_test.go
Labels: approved, lgtm, size/M
