Repository openshift-assisted/assisted-events-stream, pull requests merged in 2023-04, with the labels that each got.

#17 add production kafka instance
  terraform/main.tf
Labels: approved, lgtm, size/M

#18 NO-ISSUE: Unreachable code
  pkg/stream/reader.go
Labels: approved, lgtm, size/XS, jira/valid-reference

#20 MGMT-14208: Adding linter
  .golangci.yaml
  Dockerfile.build
  Makefile
Labels: approved, lgtm, size/M, jira/valid-reference

#21 MGMT-14208: formatting to pass lint
  internal/projection/enriched_event_projection_test.go
  internal/projection/process/anonymize.go
  internal/projection/process/event_enricher.go
  internal/projection/process/event_enricher_test.go
  internal/projection/process/host_summary_test.go
  internal/projection/process/hosts_summary.go
  internal/repository/opensearch/enriched_event_repository.go
  pkg/jsonedit/delete.go
  pkg/jsonedit/rename.go
  pkg/jsonedit/transform.go
Labels: approved, lgtm, size/L, jira/valid-reference

#19 MGMT-14180: Adding release_tag field to projected data
  internal/projection/process/event_enricher.go
  internal/projection/process/event_enricher_test.go
  internal/types/event.go
Labels: approved, lgtm, size/L, jira/valid-reference
