Repository openshift-assisted/assisted-events-stream, pull requests merged in 2024-03, with the labels that each got.

#59 undelete kind fields: used to detect day2 installations
  internal/projection/process/default_fields.go
  internal/projection/process/event_enricher_test.go
Labels: approved, lgtm, size/XS

#60 downsize to 0 replicas when index is more than 1 month old
  manifest/base/projection-template.yaml
  manifest/components/opensearch-curator/opensearch-curator.yaml
  manifest/components/redis/redis.yaml
  manifest/overlays/dev/parameters.yaml
  manifest/overlays/production/parameters.yaml
  openshift/template.yaml
Labels: approved, lgtm, size/M

#61 MGMT-17308: Offboard osherdp from maintainers list
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, jira/valid-reference
